name: Deploy master
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Install dependencies
      run: npm install
      
    - name: Build package
      run: npm run build
      
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: node_modules

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: sbucket-fe-production-0001
        environment_name: sbucket-fe-production-0001
        version_label: ${{github.run_number}}
        region: us-east-1
        deployment_package: deploy.zip
